Numpy

In [1]:
import numpy as np

In [37]:
arr = np.ones(5)

In [38]:
arr

array([1., 1., 1., 1., 1.])

In [39]:
arr1 = np.zeros(5)

In [40]:
arr1

array([0., 0., 0., 0., 0.])

In [41]:
arr3 = np.arange(2,100,2)

In [42]:
arr3

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [43]:
arr4 = np.ones(5)*10

In [44]:
arr4

array([10., 10., 10., 10., 10.])

In [45]:
arr5 = np.arange(1,17)

In [46]:
arr6 = arr5.reshape(4,4)

In [47]:
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [48]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.random.randint(5)

3

In [51]:
np.random.randn(25).reshape(5,5) # 0 ın etrafında rasgele sayı oluşturuyor. Gaussian Distribution a göre.

array([[-1.23987194, -0.3114881 ,  0.25949075,  0.06101658, -0.54715282],
       [ 0.94624167,  1.80538709,  0.75737527, -1.34495161, -0.33105386],
       [ 2.18792544,  0.1765168 , -0.69405834,  1.07613085,  0.30882343],
       [-1.67095131, -0.13423033, -0.8183473 ,  0.74725939, -0.94301573],
       [ 1.13597144,  0.07236086, -1.31309969,  1.38558251,  1.043105  ]])

In [55]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [56]:
arr  = np.arange(1,101).reshape(10,10)

In [57]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [59]:
arr[4:]

array([[ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [61]:
arr[6:,4:]

array([[ 65,  66,  67,  68,  69,  70],
       [ 75,  76,  77,  78,  79,  80],
       [ 85,  86,  87,  88,  89,  90],
       [ 95,  96,  97,  98,  99, 100]])

In [63]:
arr[:3,2:4]

array([[ 3,  4],
       [13, 14],
       [23, 24]])

In [ ]:
arr.sum()